---

- name: plugins | Download nexus plugins
  get_url:
    url={{item.url}}/{{item.file}}
    dest={{nexus_tmpdir}}
  with_items: nexus_plugins
  register: download_results 
  ignore_errors: yes
  tags: nexus

- name: plugins | Messange on dep fail
  fail: msg="For some reason nexus rep break on upgrade. Please contact Till or Adham"
  when: download_results | failed

- name: plugins | Unarchive nexus plugins
  Unarchive: 
    copy=no
    src="{{nexus_tmpdir}}/{{item.file}}"
    dest="{{nexus_plugin_dir}}/"
  sudo_user: "{{nexus_user}}"
  with_items: nexus_plugins  
  tags: nexus